### ISSUE TITLE
Drop downs/Attribute(Column) name is too small to use, list is unsorted(e.g Search properties)

### ISSUE THREAD

**Issue by saloni2409** [rakam-io/rakam#80] opened 2017-10-26 07:49 UTC

**Comment by buremba** [comment] 2017-10-26 07:57
All dropdowns or just the funnel, event explorer or retention pages?

**Comment by buremba** [comment] 2017-11-04 01:08
Wanted to follow-up on my previous message. :)

**Comment by saloni2409** [comment] 2017-11-07 06:12
For all the pages, textbox size should be dragable

**Comment by buremba** [comment] 2017-11-07 07:22
Sorry, I still don't get it. I agree that the list should be sorted so I applied a fix to do this. However; I don't think the textbox should be resizable. (I guess you meant resizable instead of draggable). Here is an example:

<img width="471" alt="screen shot 2017-11-06 at 11 17 13 pm" src="https://user-images.githubusercontent.com/82745/32481605-ef9c518c-c348-11e7-9829-7f2be15816cf.png">

Do you think that the textbox is too small or is there anything that I'm missing? You actually search for values using this textbox so it should not be too big. If you can share your use-case or show me an example GIF or screenshot, that would help.

**Comment by saloni2409** [comment] 2017-11-07 07:35
After adding multiple filters (around 7/8) textbox goes out of the screen. So either textbox or the entire frame should be draggable as well as resizable.

**Comment by buremba** [comment] 2017-11-07 07:38
I need at least one screenshot because if I don't really understand what the issue is, I can't really help. :) 
So the bug occurs only when you have 7/8 filters enabled, am I right?

**Comment by saloni2409** [comment] 2017-11-07 08:27
![image](https://user-images.githubusercontent.com/11413225/32483811-8826ef96-c3c3-11e7-8cc3-9bbd72a10d20.png)

there is no way to apply the last filter.

**Comment by buremba** [comment] 2017-11-09 00:14
It's fixed in master.

**Closed by buremba** 2017-11-09 00:14 UTC

**Comment by saloni2409** [comment] 2017-11-24 06:50
![image](https://user-images.githubusercontent.com/11413225/33198549-b6941ae2-d111-11e7-8681-d01cfcfbd9d2.png)

Unable to click on apply button.

**Comment by buremba** [comment] 2017-11-25 05:17
The problem is probably related with the previous filter `in ()`, when you do not add any item the expression becomes invalid. I fixed the bug, could you please try again?
